[package]
name = "opengl-experiment"
version = "0.1.0"
authors = ["Mick van Gelderen <mickvangelderen@gmail.com>"]

[workspace]

[dependencies]
cgmath = "0.15.0"
glutin = "0.10.0"
gl = "0.6.3"
image = "*"
simple-field-offset = { path = "simple-field-offset" }
num-traits = "0.1.40"